wllama:
	curl -o javascript/wllama.js https://github.ngxson.com/wllama/esm/index.js
	curl -o wasm/wllama.wasm https://github.ngxson.com/wllama/esm/wasm/wllama.wasm

bert:
	curl -o models/bert-bge-small/ggml-model-f16.gguf https://huggingface.co/ggml-org/models/resolve/main/bert-bge-small/ggml-model-f16.gguf
